### ISSUE TITLE
Notes page does not load properly

### ISSUE THREAD

**Issue by shirubana** [csucyberforce/CyberForceHelpIssues#2]
When I click on the notes link, the inset window times out and does not load properly.  "10.0.55.8Error setting up database. Exiting. Invalid Credentials                                                                                                                        
Session closed.                                                                                                                                                                         "

**Comment by shirubana** [comment]
still cannot access notes pages, menu does not load

**Comment by shirubana** [comment]
error on notes page:  10.0.55.8Error setting up database. Exiting. Invalid Credentials                                                                                                                         
Session closed.

**Comment by shirubana** [comment]
Problems continue with notes page though it appears they are different than above...You're on the right track

**Comment by unex** [comment]
Notes has been fixed, thank you for your patience.

**Comment by unex** [comment]
I take it back

**Comment by unex** [comment]
ok I fixed it good this time
