### ISSUE TITLE
Getting a message "something went wrong..."

### ISSUE THREAD

**Issue by shirubana** [csucyberforce/CyberForceHelpIssues#8]
Getting the message "something went wrong, connection is closed.

**Comment by shirubana** [comment]
Is anybody out there to help?  Can't get past the "HMI" step due to the "something went wrong, connection is closed." message.  Went to notes and got 
![image](https://user-images.githubusercontent.com/22824806/69000076-3c177980-0887-11ea-9acb-99ca0fe21e25.png)

**Comment by unex** [comment]
Fixed sorry about that.
